# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIComponets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'R.swift', '~>7.3.2'
  pod 'ReachabilitySwift', '~>5.0.0'
  pod 'Alamofire'
  pod 'Kingfisher'
  

  # Pods for UIComponets

  target 'UIComponetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIComponetsUITests' do
    # Pods for testing
  end

end
